/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class FrameActualizarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameActualizarCliente
     */
    public FrameActualizarCliente() {
        initComponents();
        jTNombreAc.setEditable(false);
        jTApellidosAc.setEditable(false);
        jTDireccionAc.setEditable(false);
        jTTelefonoAc.setEditable(false);
        jTEmailAc.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTCedulaAc = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTDireccionAc = new javax.swing.JTextField();
        jTTelefonoAc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTEmailAc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTNombreAc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTApellidosAc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Actualizar Cliente");

        jLabel2.setText("CI: ");

        jTCedulaAc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTCedulaAcKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTDireccionAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDireccionAcActionPerformed(evt);
            }
        });
        jTDireccionAc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDireccionAcKeyReleased(evt);
            }
        });

        jTTelefonoAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTelefonoAcActionPerformed(evt);
            }
        });
        jTTelefonoAc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTTelefonoAcKeyReleased(evt);
            }
        });

        jLabel5.setText("Email:");

        jTEmailAc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTEmailAcKeyReleased(evt);
            }
        });

        jLabel4.setText("Teléfono:");

        jLabel7.setText("Dirección:");

        jLabel3.setText("Nombres:");

        jTNombreAc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTNombreAcKeyReleased(evt);
            }
        });

        jLabel6.setText("Apellidos: ");

        jTApellidosAc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTApellidosAcKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTTelefonoAc, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jTEmailAc, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jTDireccionAc, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jTApellidosAc)
                    .addComponent(jTNombreAc))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTNombreAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTApellidosAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTDireccionAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTTelefonoAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTEmailAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jButton1.setText("Buscar");

        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "C.I.", "Nombres", "Apellidos", "Dirección", "Teléfono", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2)
                                .addGap(63, 63, 63)
                                .addComponent(jTCedulaAc, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jBActualizar)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTCedulaAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDireccionAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDireccionAcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDireccionAcActionPerformed

    private void jTTelefonoAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTelefonoAcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTelefonoAcActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jTNombreAc.setEditable(true);
        jTApellidosAc.setEditable(true);
        jTDireccionAc.setEditable(true);
        jTTelefonoAc.setEditable(true);
        jTEmailAc.setEditable(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jTCedulaAcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCedulaAcKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Pattern pat = Pattern.compile("^[0-2]{1}[0-9]{9}");
            Matcher mat = pat.matcher(this.jTCedulaAc.getText());
            if(mat.matches()){
                
            }else{
                JOptionPane.showMessageDialog(null, "Cédula incorrecta,"
                        + " por favor ingrese una cédula válida");
                this.jTCedulaAc.requestFocus();
            }
        }
    }//GEN-LAST:event_jTCedulaAcKeyReleased

    private void jTNombreAcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreAcKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Pattern pat = Pattern.compile("[A-Za-z\\s]{20}");
            Matcher mat = pat.matcher(this.jTNombreAc.getText());
            if(mat.matches()){
                this.jTApellidosAc.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos,"
                        + " por favor verifiquelos e intente ingresar de nuevo");
                this.jTNombreAc.requestFocus();
            }
        }
    }//GEN-LAST:event_jTNombreAcKeyReleased

    private void jTApellidosAcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidosAcKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Pattern pat = Pattern.compile("[A-Za-z\\s]{20}");
            Matcher mat = pat.matcher(this.jTApellidosAc.getText());
            if(mat.matches()){
                
            }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos,"
                        + " por favor verifiquelos e intente ingresar de nuevo");
                this.jTApellidosAc.requestFocus();
            }
        }
    }//GEN-LAST:event_jTApellidosAcKeyReleased

    private void jTDireccionAcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDireccionAcKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Pattern pat = Pattern.compile("[A-Za-z\\s]{50}");
            Matcher mat = pat.matcher(this.jTDireccionAc.getText());
            if(mat.matches()){
                
            }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos,"
                        + " por favor verifiquelos e intente ingresar de nuevo");
                this.jTDireccionAc.requestFocus();
            }
        }
    }//GEN-LAST:event_jTDireccionAcKeyReleased

    private void jTTelefonoAcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTelefonoAcKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Pattern pat = Pattern.compile("^[0]{1}[2-7]{1}[0-9]{7}");
            Matcher mat = pat.matcher(this.jTTelefonoAc.getText());
            if(mat.matches()){
                
            }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos,"
                        + " por favor verifiquelos e intente ingresar de nuevo");
                this.jTTelefonoAc.requestFocus();
            }
        }
    }//GEN-LAST:event_jTTelefonoAcKeyReleased

    private void jTEmailAcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEmailAcKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Pattern pat = Pattern.compile("^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$");
            Matcher mat = pat.matcher(this.jTEmailAc.getText());
            if(mat.matches()){
                
            }else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos,"
                        + " por favor verifiquelos e intente ingresar de nuevo");
                this.jTTelefonoAc.requestFocus();
            }
        }
    }//GEN-LAST:event_jTEmailAcKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApellidosAc;
    private javax.swing.JTextField jTCedulaAc;
    private javax.swing.JTextField jTDireccionAc;
    private javax.swing.JTextField jTEmailAc;
    private javax.swing.JTextField jTNombreAc;
    private javax.swing.JTextField jTTelefonoAc;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
